name: Dagelijks Weerfeitje

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  send-weather-fact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Random Weather Fact
        id: fact
        run: |
          FACT=$(shuf -n 1 facts.txt)
          echo "FACT=$FACT" >> "$GITHUB_OUTPUT"

      - name: Verzend naar Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content '${{ steps.fact.outputs.FACT }}' '{content: $content}')"
