name: Eclipse Alert Nederland

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  eclipse:

    runs-on: ubuntu-latest

    steps:

      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python installeren
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Pakketten installeren
        run: |
          pip install -r requirements.txt

      - name: Eclipse controle
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python eclipse_check.py
