name: Eclipse Alert Nederland

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  eclipse:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - name: Controle
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python eclipse_check.py
